name: souq_souda
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter

#for splash screen
  flutter_native_splash:
#Responsive Screen
  flutter_screenutil:
#networking
  dio:
  pretty_dio_logger:
#state management
  flutter_bloc:
  bloc:
  equatable:
#Functional Programming in Dart
  dartz:
#for dependency injection
  get_it:
#for image from network
  cached_network_image:
#for fl_chart
  fl_chart: 
#for check about responsive
  device_preview: ^1.2.0
  expandable:
#for save data
  shared_preferences:
  expansion_tile_group:
  intl:
  line_chart:
  d_chart: ^2.6.9
  syncfusion_flutter_charts:
  flutter_secure_storage: ^9.2.2

  #for html images
  flutter_widget_from_html_core:
  fwfh_cached_network_image: ^0.14.2
  #local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #cache local data
  build_runner: ^2.4.11
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
